### ISSUE TITLE
Advertise Additional Capabilities 

### ISSUE THREAD

**Issue by JoelBCarter** [Microsoft/vsts-agent-docker#107]
Is there a way to allow an agent (assuming we inherit from one of these containers) to advertise additional capabilities to VSTS?  I believe the term for these are [User Capabilities](https://docs.microsoft.com/en-us/vsts/build-release/concepts/agents/agents?view=vsts#capabilities).  As it is currently, I'm manually adding capabilities for each agent from VSTS, but it would be nice to have the agent do that in a way that VSTS can discover the capabilities.  For example right now `yarn` is required for some of our `Node.js` projects but even with `yarn` installed on our container, VSTS doesn't recognize it's there unless I manually add that capability via the UI.  Yarn is possibly a bad example here because I assume there'll be support for that in the base container soon enough, but even beyond that, is/will there be some mechanism for broadcasting to VSTS additional agent capabilities beyond what we can expect to be included in VSTS base image.

**Comment by dakale** [comment]
I dont believe there is an automated way to add User Capabilities, you would need to add that via the UI. You can just add system capabilities though, which are just your environment variables. 

See: https://github.com/Microsoft/vsts-agent-docker/blob/master/ubuntu/start.sh#L4

Well known (by VSTS) variables get ignored but you can export whatever you want. Since you are using containers just `docker run` with `-e HAS_YARN=true` for eg. Or use the appropriate mechanism if you are using Kubernetes/something else.

You could also use ENV in your Dockerfiles that are based on this agent

**Comment by JoelBCarter** [comment]
Yes!  Looking at the **SYSTEM CAPABILITIES** in the admin tab for the agents, it appears that a capability is nothing more than just an environmental variable.

![image](https://user-images.githubusercontent.com/5701833/40513816-8bbbd78a-5f6c-11e8-80a9-3164c41f0de7.png)

Since that's the case I can just create an environmental variable in my container corresponding to the capability I'd like the container to advertise and I'm done.  I don't really care that it shows up as a System Capability and not a User Capability.  What matters as long it it's there to filter on when selecting an available agent.  Thanks @dakale.  I'm closing this issue as it's solved, but it'd great if this was explicitly documented somewhere as adding capabilities seems like something others might wonder about in the future too and it really is just that simple.
