### ISSUE TITLE
update dotnet version

### ISSUE THREAD

**Issue by Franklin89** [Microsoft/vsts-agent-docker#12]
I wanted to use the ubuntu-16.04-docker-1.12.1-standard image to run my .net core build. I am using VS2017 RC for development. The build output shows that that a older version of dotnet is installed.

/usr/bin/dotnet --version
1.0.0-preview2-003131

Task         : Command Line
Description  : Run a command line with arguments
Version      : 1.1.2
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)

/usr/bin/dotnet restore xxx.sln
error: Invalid input 'xxx.sln'. The file type was not recognized.
/usr/bin/dotnet failed with return code: 1
/usr/bin/dotnet failed with error: /usr/bin/dotnet failed with return code:

**Comment by stepro** [comment]
We should update the dotnet version to something more recent. @chrisrpatterson how do you want to deal with versions of tools inside the standard image? If we update it, then everyone will receive the update, that is, there's no way to easily lock down to a particular snapshot of tool versions.

**Comment by stuartleeks** [comment]
Now that VS2017 is RTM, can we get a version of the vsts-agent with the RTM .NET Core SDK installed?

**Comment by stepro** [comment]
That makes sense. Let me see if I can publish a refresh of the images today.

**Comment by stuartleeks** [comment]
Thanks - that would be great! Save me messing around to create a custom image :-)

**Comment by stuartleeks** [comment]
Hi @stepro - just bumping this :-)

**Comment by stepro** [comment]
@chrisrpatterson<mailto:Chris.Patterson@microsoft.com>, I'm unsure of the implications of doing this. If there are compatibility breaks between 1.0.0-preview2-003131 and RTM (quite possible), blindly updating the "standard" image, which isn't versioned, is going to cause problems. I think we might want to move at least to a model where the standard images are followed by a version indicator, even if it's something like "20171303" indicating the date on which it was built, so that people can lock down to a specific set of versions of tools if they so desire.

If you agree, I'd take the existing standard images and re-tag them with the date they were published (20161214) and re-purpose the current un-versioned ones as equivalent to "latest" standard image. This means that people might receive a one-time break, at which point they should lock down to a particular build.

**Comment by stuartleeks** [comment]
If you do that, it would be really helpful to have a page that lists each tagged version and what is contained within it (including versions) :-)

**Comment by stepro** [comment]
Yes I think having a date based tag is a good idea.

I was also thinking about the model we have around repositories.  Is it the right thing to have a single repository for the agent and then dozens of tags or should we really have a different repository for each flavor of the agent.  For example you don’t have a single repository for windows and then tags for servercore and nanoserver.

From: Stephen Provine
Sent: Monday, March 13, 2017 12:10 PM
To: Microsoft/vsts-agent-docker <reply@reply.github.com>; Microsoft/vsts-agent-docker <vsts-agent-docker@noreply.github.com>; Chris Patterson <Chris.Patterson@microsoft.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Microsoft/vsts-agent-docker] update dotnet version (#12)

@chrisrpatterson<mailto:Chris.Patterson@microsoft.com>, I'm unsure of the implications of doing this. If there are compatibility breaks between 1.0.0-preview2-003131 and RTM (quite possible), blindly updating the "standard" image, which isn't versioned, is going to cause problems. I think we might want to move at least to a model where the standard images are followed by a version indicator, even if it's something like "20171303" indicating the date on which it was built, so that people can lock down to a specific set of versions of tools if they so desire.

If you agree, I'd take the existing standard images and re-tag them with the date they were published (20161214) and re-purpose the current un-versioned ones as equivalent to "latest" standard image. This means that people might receive a one-time break, at which point they should lock down to a particular build.

**Comment by stepro** [comment]
We could choose to separate Windows and Linux into separate Docker Hub repositories. It's worth pointing out that most repositories on Docker Hub do tend to support multiple base Linux OS images, e.g. ubuntu, alpine, centos. While supporting various Windows base OSes is clearly a bigger jump, I think it wouldn't be unexpected if we kept everything in one repository. On the other hand, there is the issue of having to document a large number of tags (there are already many) and adding Windows to the mix would create many more.

I figure we can keep the same GitHub repo under the covers but if you'd like to have a separate repository for the Windows images (of all the base OS flavors), I'd be fine with that. I don't think it's necessary to separate each Windows base OS into different repositories for the same reason that there's a single "node" repository with debian and alpine based images.

From: Chris Patterson
Sent: Tuesday, March 14, 2017 6:57 AM
To: Stephen Provine <stephpr@microsoft.com>; Microsoft/vsts-agent-docker <reply@reply.github.com>; Microsoft/vsts-agent-docker <vsts-agent-docker@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Microsoft/vsts-agent-docker] update dotnet version (#12)

Yes I think having a date based tag is a good idea.

I was also thinking about the model we have around repositories.  Is it the right thing to have a single repository for the agent and then dozens of tags or should we really have a different repository for each flavor of the agent.  For example you don’t have a single repository for windows and then tags for servercore and nanoserver.

From: Stephen Provine
Sent: Monday, March 13, 2017 12:10 PM
To: Microsoft/vsts-agent-docker <reply@reply.github.com>; Microsoft/vsts-agent-docker <vsts-agent-docker@noreply.github.com<mailto:vsts-agent-docker@noreply.github.com>>; Chris Patterson <Chris.Patterson@microsoft.com<mailto:Chris.Patterson@microsoft.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: RE: [Microsoft/vsts-agent-docker] update dotnet version (#12)

@chrisrpatterson<mailto:Chris.Patterson@microsoft.com>, I'm unsure of the implications of doing this. If there are compatibility breaks between 1.0.0-preview2-003131 and RTM (quite possible), blindly updating the "standard" image, which isn't versioned, is going to cause problems. I think we might want to move at least to a model where the standard images are followed by a version indicator, even if it's something like "20171303" indicating the date on which it was built, so that people can lock down to a specific set of versions of tools if they so desire.

If you agree, I'd take the existing standard images and re-tag them with the date they were published (20161214) and re-purpose the current un-versioned ones as equivalent to "latest" standard image. This means that people might receive a one-time break, at which point they should lock down to a particular build.

**Comment by stepro** [comment]
I have pushed some versioned standard images that include dotnet 1.0.1. You can find details of what's in the versioned images (currently, only 20170315) in the ubuntu/derived/standard README.md.

**Comment by stuartleeks** [comment]
Great news. I'm out of the office today, but will give this a test tomorrow :-)
Thanks!

**Comment by stepro** [comment]
I have updated the documentation to fully describe which standard images include dotnet 1.0.1 and the latest standard image now uses this version.

**Comment by stuartleeks** [comment]
Thanks @stepro :-)
