### ISSUE TITLE
Add Docker Agent to Deployment Group

### ISSUE THREAD

**Issue by borigas** [Microsoft/vsts-agent-docker#146]
Is there a way to add a docker agent to a deployment group?

**Comment by dakale** [comment]
Its possible but not something we officially support, plan to support, or recommend. These images are for disposable build environments, primarily. 

If you want to deploy your software as containers, you should build your containerized application in a build pipeline, rather than copy your application into a container after the fact using deployment groups, and deploy to one of the various container platforms that Azure offers (https://azure.microsoft.com/en-us/overview/containers/) or any container platform on Swarm, Kubernetes, etc. But deployment groups are meant mostly for targeting eg self hosted VMs.
