### ISSUE TITLE
Future of this repo after Hosted Linux Preview pool deprecation?

### ISSUE THREAD

**Issue by drch-** [Microsoft/vsts-agent-docker#161]
The hosted Linux preview pool will be retired in a couple weeks

Is this repo going to continue to be updated with the latest tools installed on the hosted Ubuntu pool?  Or will it be deprecated along with the preview?

**Comment by dakale** [comment]
See my comment [here](https://github.com/Microsoft/vsts-agent-docker/issues/167) for a little more info. We moved to generating VM images to support the hosted pools, and there is far too much on each image to be useful in container scenarios (dozens of GBs), so there are no plans to keep the set of software installed in these container matching the software on the hosted machines. 

I want to encourage people to build their own images `FROM` one of the lighter weight images here (:ubuntu-14.04, or ubuntu-16.04 tags) because youll have a much lighter image with more control, can install what you need when you need it, etc. 

Software on these images will probably be "update only" (not planning on adding any entirely new software) but can be updated depending on widespread need. Seems like thats mostly dotnet for now but need to wait and see. 

Not sure if that is a definitive plan for long term, but for now it seems like most peoples need will be met if these images are just left alone and trend towards conservatively trying not to break people, rather than moving them forward 

Hope that helps
