### ISSUE TITLE
containeragent lost communication with the server

### ISSUE THREAD

**Issue by muziekklas** [microsoft/vsts-agent-docker#163]
Hey there,
First of all, Great work of making the build agent available in Docker!
I have a Angular Build which takes some time (AOT & Maps are taking a while).
I've used the Ubuntu 16.04 docker file (slightly adapted it so I have all capabilities) but it keeps failing with the message in Azure Devops:
The agent: containeragent lost communication with the server. Verify the machine is running and has a healthy network connection. For more information, see: https://go.microsoft.com/fwlink/?linkid=846610 

I am hosting it in a Azure Container Instance.
Is this related to the Container Instance or is it due to a wrong configuration of the agent?

Thanks in advance!

**Comment by dakale** [comment]
I would guess it is an issue with connectivity in ACI

If the agent container is able to start and connect to Azure Pipelines, and start the job, then youve certainly configured and started the agent correctly

Did you modify the start.sh script for your image?

**Comment by muziekklas** [comment]
Thank you for your quick reply!
Well, I have only removed dependencies like php and stuff which I didn't need.
I didn't change the startup file.

Any ideas why devops is losing coonectivity to ACI?  Could it be that the container restarts cause its host thinks it crashed?

Thanks in advance

**Comment by muziekklas** [comment]
I've made a discovery today. When building a complex angular project with tons of features, it crashes (nodejs heap exception). When I build the new project which is still small, no issues at all. So I assume that it is the Memory issue in Angular CLI in my case. Ill keep researching the issue  and keep you guys posted

**Comment by dakale** [comment]
Thank you for the update @muziekklas 

@magnock - because you are in Kubernetes and this issue seems related to the container using too much memory and getting killed, you may need to set resource (memory) requests for the pod matching the expected memory usage of your build so that pods will not get over scheduled on nodes and exhaust the memory. Are you also using angular? 

@muziekklas I found this page regarding ACI: https://docs.microsoft.com/en-us/azure/container-instances/container-instances-monitor Are you able to run some builds and look at memory usage for the container group? I have not really used ACI but I am wondering if having multiple containers running is exhausting your memory quota for the group they are running in
