### ISSUE TITLE
How do I disable auto-update on ubuntu 16.04 containers

### ISSUE THREAD

**Issue by grahamsk** [Microsoft/vsts-agent-docker#173]
Hi All,

I would like to disable auto-update for my vsts agents running on ubuntu 16.04 docker containers.

Could you please let me know how I go about doing this?

Thanks,
Graham

**Comment by dakale** [comment]
There is some information on that here: https://github.com/Microsoft/vsts-agent-docker/issues/63

In general, depending on exactly what you mean, the answer will be "you cant", because the agent needs to be up to a minimum version to match functionality with Azure DevOps apis, which are hosted and move forward. 

For on prem, the TFS tagged images download a set agent version and do not move forward relative to your version of TFS

Hope that helps
