### ISSUE TITLE
Slim agent for docker

### ISSUE THREAD

**Issue by noadmin** [Microsoft/vsts-agent-docker#174]
Hi all,
Is it any chance to get really small agent for docker from stock? I'm talking about not including all those unneeded extensions such as chrome, nodes etc. For example on Alpine base. Because, `ubuntu-16.04-standard 4 GB` is overkill for modern ci/cd.
Regards.

**Comment by dakale** [comment]
`ubuntu-16.04` (not standard) is just a plain image without any extra tools installed. Its Ubuntu based so not as slim as alpine but its only ~300mb uncompressed vs `*-standard` which are ~10gb uncompressed

Hope that works for you. We have no plans to release an alpine based version of this in the near future because the agent itself has glibc dependencies and the work hasnt been done yet. A lot of that size is the agent anyways, so changing the base wont make a huge difference 

Let me know if you have any questions

**Comment by bricerisingslalom** [comment]
Outside of the os, the current vsts agent comes with a lot of packages installed on it that makes the image extremely large. Could we get a distributed image that only comes with the vsts agent installed on it on the ubuntu base image so that we can choose our own dependencies to install on it?
