### ISSUE TITLE
How can I install Nuget,MSBUILD,Webdeploy

### ISSUE THREAD

**Issue by seven1986** [Microsoft/vsts-agent-docker#24]
Now,I use ubuntu-16.04-tfs-2017-docker-17.03.0-ce-standard for build agent, very good, thanks!
But I need Nuget、MSBUILD、Webdeploy， could you tell me how can I include this in the image?

**Comment by stepro** [comment]
The current dotnet tools in the image include MSBuild, so that should be covered. I think Nuget might be part of that as well. I don't know if there is a .NET Core build of Webdeploy. In general, it's going to be hard to include all the tools that cover a majority of the VSTS tasks because many of them require tools that are only Windows based.

Can you tell me which specific tasks you are trying to run? I should be able to identify whether there is a path to success with the Linux agent images for those tasks or not.

**Comment by seven1986** [comment]
![image](https://cloud.githubusercontent.com/assets/20808494/25111314/c9bbae98-241c-11e7-90b1-313a2c770839.png)
We use this task

**Comment by stepro** [comment]
@chrisrpatterson, is there any expectation that the existing MSBuild task will work with the Linux-based images? Given that the dotnet toolset comes with a version of MSBuild now?

**Comment by chrisrpatterson** [comment]
No we don't have any plans for those changes as there is currently only a small set of MSBuild tasks and targets that work on Linux and those are targeted for .NET Core so you should just use dotnet build and let that call MSBuild directly.  WebDeploy does not exist for Linux and I do not know of any plans in that area.

**Comment by seven1986** [comment]
@stepro  @chrisrpatterson  Thanks for your help!
and， are there some ideas that I can build and publish my aspnet core project? thanks

**Comment by stepro** [comment]
I believe there are some VSTS tasks that work for ASP .NET core projects. Look for a template called "ASP .NET Core (PREVIEW)" when creating a new build definition.

**Comment by seven1986** [comment]
谢谢啦❤❤
