### ISSUE TITLE
Improve linux based agents to run under a vsts:vsts id instead of root

### ISSUE THREAD

**Issue by xynova** [Microsoft/vsts-agent-docker#45]
I guess this would be more of an improvement to tighten security. Currently if I run as root, that agent can potentially hack into the system or have access to all other containers running on the same engine.

https://github.com/Microsoft/vsts-agent-docker/blob/0d013f268898773a6d85db3ba8c2a14f3c82ea50/ubuntu/start.sh#L63

**Comment by stepro** [comment]
We started here, but for a variety of reasons this didn't work out. One of the reasons I remember had to do with when the VSTS agent is used for running tasks that are themselves containerized (e.g. enabled via the built-in Docker and Docker Compose tasks).

The common usage of Docker to run tasks involves sharing the cloned source code via a volume map, so the VSTS agent syncs the code and the task (in a completely different container) operates on it. The key problem here is that most Docker images are built to run as root, so if you use such a container to create intermediate files, those files will be owned by root. If the agent itself runs as a vsts user, it is unable to further manage those files. For instance, performing a clean sync is no longer possible.

We decided to accept the Dockerized VSTS agent running as root because in reality, Docker is not a security boundary of any kind. While running as a non-root user makes it somewhat more secure, it isn't a truly secure solution.

**Comment by xynova** [comment]
I understand the problem and yes, Docker and root is a bit of a face palm. Having said this, an option is to enable vsts user as a sudoer through a switch when creating the agent. I find the agent truly useful for pushing and deploying stuff into on prem or private vnet machines. I am thinking about using gosu to tighten the security and see how it goes similar to what nginx container does or used to do at least.

**Comment by xynova** [comment]
There are a few things that can be done to ensure security when running docker. 

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html-single/container_security_guide/

**Comment by xynova** [comment]
just read this about sudo

You should avoid installing or using sudo since it has unpredictable TTY and signal-forwarding behavior that can cause more problems than it solves. If you absolutely need functionality similar to sudo (e.g., initializing the daemon as root but running it as non-root), you may be able to use “gosu”.

**Comment by stepro** [comment]
If you run as a non-root user that is a sudoer or equivalent, then surely a malicious task could invoke such an action and therefore gain root access to the container. It looks like the preferred approach to trying to secure a Docker container is to remove capabilities so that even if it runs as root, that root isn't able to do many of the things that root on the host can do. Just remember that if you choose to enable the VSTS agent to manage additional Docker containers by bind mounting /var/run/docker.sock, you're effectively giving the agent full access to the host, and there's no way around that.

Can you elaborate on your scenario of "pushing and deploying stuff into on prem or private vnet machines"? Why does this require tightened security on the VM that is hosting the VSTS agent in a container? Are you trying to share the same VM to run both the agent and the things you are deploying? I would advise against doing that and instead have a VM that is dedicated to the agent (it may be in the same vnet so it can see the target VMs).

**Comment by xynova** [comment]
I would just enable sudo or gosu in cases where root privileges are required and try to drop everything else by default. Reaching the perfect security spot takes time and can really only be done incrementally one step every time.

I am not using docker to build docker nor to orchestrate containers. The scenario where I want to restrict security is the following: I am using VSTS to push ansible playbooks into onprem VMs through an VNET SSH bastion gateway. I am running Ansible in a container along with the vsts agent. I will use the same docker VM to run another agent that has other tasks that require much less capabilities. 

I noticed the start.sh script has both the agent download and start combined and I would have to break it down if I wanted to use gosu (go sudo) on it. For the time being I will probably try enforcing selinux https://coreos.com/os/docs/latest/selinux.html and as you mention drop capabilities.

The environment is a bit sensitive too.. I just prefer to play it safe from the start.

**Comment by xynova** [comment]
it seems to be happy with setenforce 1 and --cap-drop=all --cap-add=chown --cap-add=fowner
