### ISSUE TITLE
Question: How to prepare for strucktural changes in this repo

### ISSUE THREAD

**Issue by kirkone** [Microsoft/vsts-agent-docker#47]
Hello,

I am working on a Pull request with some more platforms. I am working on CentOS and Windows Server images at the moment.
In preparation for this I want to rearrange some files and folders. Should I provide a single PR with all changes or should I provide a PR with this Folder changes first?

I hope this is the right place to ask.
Greetings, KirK

**Comment by stepro** [comment]
Can you give a brief description of the file/folder rearrangement? Or if you have already made these changes, feel free to submit a pull request with just those changes first and I'll take a look. Thanks!

**Comment by kirkone** [comment]
This is what I have so far:
![image](https://user-images.githubusercontent.com/15778270/30105162-0b8bdb78-92f8-11e7-9ef7-1a03324a20d0.png)

The plan is to get this integrated in this repo. I think the main point is to devide Windows and Linux.

**Comment by stepro** [comment]
Ok, so is it fair to say that what you've done is to move the existing ubuntu directory under the Linux directory, and moved the existing build.sh, dirs.sh, push.sh and update.sh into the ubuntu directory? And then created a sibling directory with similar artifacts for the centos images? This seems reasonable. We'd want to keep latest.tag and tags-md.sh in the root.

**Comment by kirkone** [comment]
Hi,
this image is from a working dir not related to this repo but I want to integrate my work in this repo.
I think the best start ist to do a PR with the folder changes first and than later on to integrate CentOS and Windows.
I will start working on this first PR asap.

Should I leave this issue open as a discussion place for the PR?

Greetings, KirK

**Comment by kirkone** [comment]
@stepro I am not sure how the latest.tag have to look like when there are multiple OS. Maybe it is not the best idea to have one image name with tags for 3 different systems because of there can only be one latest. But which one should it be?
In the end there will be tags like this:

microsoft/vsts-agent:ubuntu-16.04-...
microsoft/vsts-agent:centos-7.3.1611-...
microsoft/vsts-agent:windows-core-1703-...

This are completely different images and I am not sure about this :worried:

As a suggestion I want to add something like this:

microsoft/vsts-agent-ubuntu:16.04-...
microsoft/vsts-agent-centos:7.3.1611-...
microsoft/vsts-agent-windows:core-1703-...

Minor change but much more possibilities :stuck_out_tongue_winking_eye:
In this case the root for each system should be in its corresponding folder.

Is this something to consider?

Greets, KirK

**Comment by stepro** [comment]
The issues you raise are the reason why we didn't get into multiple OSes yet. There has been some internal discussion as to whether we should have multiple Docker Hub repositories and/or multiple GitHub repos to represent all the eventual image combinations.

While there is some precedence starting now for single image repositories containing both Linux and Windows images, I have not seen repositories that provide different images for different Linux distributions except for cases of "large" (e.g. Ubuntu) vs. "small" (e.g. alpine based). It was a stated goal originally to create images across a variety of OSes, I think because different people have different preferences on the distributions they would like to use to run their VSTS agent and tasks.

However, you could ask the same question about any of the official images. I don't, for instance, get a choice with the official "node" image of whether I want a debian or centos base. I get a choice between debian (large) or alpine (small). So I've gone back and forth on whether I want to go to the extent you are suggesting.

It would be useful for me at this point if you can enumerate some of the scenarios behind creation of a centos flavor. Currently, I'm wondering if it makes sense to align more with other official images and offer something simpler along these lines:

microsoft/vsts-agent:... (the large, Ubuntu based images)
microsoft/vsts-agent:alpine-... (smaller, alpine based images, if this even makes sense)

Regarding Linux vs. Windows, I'd likely want to adopt the multi-arch image model that is currently illustrated best by the [microsoft/dotnet](https://hub.docker.com/r/microsoft/dotnet/) repo, where the exact same image name and tag can be used and which actual image is pulled depends on the architecture of the client.

Do you have any thoughts on all of this?

**Comment by kirkone** [comment]
Hi,

the reason for choosing CentOS was by demand of a customer who wanted a dotnet core app that has to be build on CentOS (do not ask my why). So I started building my own images heavily based on this repo. You mentioned in the readme that CentOS is planned also, so I thougt this is my chance to do my part for this. In my spare time I fiddled around with the Windows images and translated the .sh scripts to .ps1. I have to say all this is quite new to me and I do not have many experience with docker and linux at all.

The idea behind the dotnet repo seems to be a good base for this here also, I think. But does this mean that there can not be a "latest" tag? If I got this right there has to be a "latest" tag for each image type, right?
One thing i did not get jet is how to build all images in one run becouse the win images has to be build compleatly different. This is the main reason behind my thinking about the separation. But after your explanation I changed my mind.

The alpine images seems realy interesting too, but at the moment there is no knowlage about this on my side.

Thanks for your time, KirK

**Comment by stepro** [comment]
Ok. If we want to proceed with CentOS support, we will need to choose some defaults so that there can be a "latest" tag. There can be different latest images for different architectures (e.g. Linux amd64 vs. Windows amd64), but not different latest images within a particular architecture (e.g. Ubuntu vs. CentOS), so we'll need to decide that one of these is the default Linux amd64 OS. I think that we should stick with Ubuntu as the default, since the VSTS agent seems to support that one best. Therefore the latest tag would continue to be something like "ubuntu-16.04-docker-17.06-ce-standard".

Regarding builds, everything is manually right now and I think with additional OSes this will become a multi-step manual process. Eventually I'd like to find a way to move to use Docker Hub's automated build, but for now it will remain manual. If you can work on changing the directory structure and getting the CentOS images defined, once I've signed off on the PRs I'll perform the manual steps and push the images to Docker Hub.

**Comment by stepro** [comment]
Thanks @nschonni. What they are doing in the docker-node repo makes a lot of sense. @kirkone, I need to think about this a little. Feel free to send a PR for what you have so we can review it.

**Comment by stepro** [comment]
I've recently checked in some changes that revamp how the images are built to optimize for faster build times. During this time I considered options for larger structural changes, but I ultimately decided that the structure of the repo was relatively sound given the unique requirements of the VSTS agent images in terms of a multi-dimensional matrix of supported combinations. The only thing missing at this point is a manifest.json file to enable the Docker Hub repository to be multi-arch (essentially, giving a latest tag for both Linux and Windows combinations), but until there is an official Windows image this is not really needed.

@kirkone, you should probably sync up with the changes I made in the various shell scripts to maintain some consistency for the CentOS and Windows flavor. I look forward to seeing what you have done. Thanks for the help!

**Comment by kirkone** [comment]
Hi,

sorry for being late on this but I had some head aches while thinking the best way to get this right.
I put my work for the windows agents on hold because I ran inti some trouble to get it working with our company proxy.
I will put together my work so far to add the centos support and in the next step we can decide what is the best way to add the windows images.
I will go over all my scripts to get your changes in.
Hopefully I will have the PR ready soon.

So long, KirK

**Comment by stepro** [comment]
Hi @kirkone, sorry for the long delay here - this dropped off my notification list. Please feel free to submit a PR from your fork to the main repository so that I can more easily review the code and add comments.

**Comment by stepro** [comment]
Closing this issue for now. There is likely to be some kind of change in the future, but it is not immediately necessary.
