### ISSUE TITLE
Agent updates do not work, 2.124.0 latest version available

### ISSUE THREAD

**Issue by adriaanthomas** [microsoft/vsts-agent-docker#63]
Using `ubuntu-16.04-standard`, at this moment `https://$VSTS_ACCOUNT.visualstudio.com/_apis/distributedtask/packages/agent?platform=ubuntu.16.04-x64` returns largest version 2.124.0 (`https://github.com/Microsoft/vsts-agent/releases/download/v2.124.0/vsts-agent-ubuntu.16.04-x64-2.124.0.tar.gz`), so this is what `start.sh` will download and install when the container is started.

When an agent update is triggered (in our case, this appears to happen when we run a yaml build), we get the following:

```
Agent update in progress, do not shutdown agent.
Downloading 2.126.0 agent
Waiting for current job finish running.
Generate and execute update script.
Agent will exit shortly for update, should back online within 10 seconds.
/vsts/agent/_work/_update.sh: line 31: ping: command not found
/vsts/agent/_work/_update.sh: line 31: ping: command not found
/vsts/agent/_work/_update.sh: line 31: ping: command not found
[...]
```

After many more identical messages the container eventually exists.

Looking at [the agent update script for Linux](https://github.com/Microsoft/vsts-agent/blob/f7e9a7ee42d0c30f0d31d449bb51d95bd6e9e0fb/src/Misc/layoutbin/update.sh.template#L37), the `ping` program is used in two places, but this is not available in the mentioned image.

Adding `ping` (`apt-get install iputils-ping`) only marginally improves things, as the container will simply exit after the `Agent will exit shortly for update` message. Restarting the agent will download version 2.124.0 again, so effectively running yaml builds in docker agents does not work.

I'm not sure if the changed agent binary URLs have something to do with this (not using the latest version from the start that is).

**Comment by cameronattard** [comment]
I think this will be resolved by https://github.com/Microsoft/vsts-agent-docker/pull/59

**Comment by stepro** [comment]
The issue here is that while the container determines the most appropriate VSTS agent version on startup, and will not be upgraded without an explicit user gesture in the VSTS UI, it will still get upgraded if it tries to run a task that requests an upgrade. This scenario was previously unknown to me, but I believe you can disable this auto-update behavior by setting the environment variable "agent.disableupdate" to a non-empty value. @adriaanthomas, can you try setting this as an environment variable when you run your container and see if that at least causes the task to fail? Which task is it that causes an agent update?

**Comment by adriaanthomas** [comment]
Setting `ENV agent.disableupdate=true` indeed prevents the agent from updating.

My build does not report any particular task to fail, it just stays in a state "Waiting for an enabled agent. All possible agents are disabled." Besides it appears that the update trigger comes from trying to run a [yaml build](https://docs.microsoft.com/en-gb/vsts/build-release/actions/build-yaml), as my "classic, GUI-created" builds still work and don't trigger updates.

After attempting to start the yaml build, the Agent Queues view now shows a message "Sent agent update message, agent will auto-update shortly." for my build agent, but as said that doesn't actually happen.

To me it looks like #59 might indeed fix this, I suggest keeping this ticket open until I can verify that.

**Comment by stepro** [comment]
It's true that #59 will resolve your immediate issue, because that will ensure that the latest version of the agent is installed so it doesn't need to dynamically upgrade when you try to do a yaml build. However, this issue is more general: a VSTS agent running at a version that was deemed the latest when it was started always has the possibility of being dynamically upgraded at some point.

I'll be accepting #59 and updating the images so this should resolve your immediate problem, but I'd like to keep this issue open to track how the general issue should be resolved. Either the container should always set agent.disableupdate to true, forcing consumers of the container to manually restart the container to pick up a newer version, or it needs to allow for dynamic restarts. The latter is obviously desirable but it's a little harder to figure out how the start script should do that.

**Comment by adriaanthomas** [comment]
I had considered if, for Docker agents, `agent.disableupdate` should always be set to `true` too, but in the end I guess that will hide (possible) agent updates (they would only be visible on the Agent Queues tab, and even there the message displayed suggests that an update will happen anyway, which it won't) and many people will end up hardly ever actually updating their agents.

While the current behaviour is not ideal, at least the container stops after installing the new agent, so it is clear something has to happen (and that `ping` is missing ;)). And I would expect that in production most people run these containers with some sort of restart policy / minimum count. Upon an automatic restart, the latest version of the agent would be downloaded again (unless stored in a volume) and the agent is at least updated.

The biggest problem at this moment, before #59, is that it is impossible to have an agent running a newer version than 2.124.0, due to the new URLs. After #59 at least it is possible to update agents again, by restarting them, even if as you say it is not the ideal solution.

**Comment by stepro** [comment]
#59 is merged and ETA is 2 hours for the images on Docker Hub to be updated. I'll respond to this issue when that process has completed.

**Comment by qmfrederik** [comment]
At least on Kubernetes, an agent auto-restarting itself will simply trigger Kubernetes to re-launch the base container, so you'll end up with an endless reboot loop.

#59 and `ENV agent.disableupdate=true` should fix things for me, though.

**Comment by stepro** [comment]
The images have been updated.

**Comment by stepro** [comment]
In most cases, this issue will no longer occur since #59 means the latest agent will be downloaded on startup. Until there is something better, you can avoid the larger issue by either passing "-e agent.disableupdate=true" when you run your container, or run it in a mode where it automatically restarts (when the agent exits due to an upgrade, the container will exit, but get recreated and should then download the latest version, effectively upgrading).

**Comment by danielearwicker** [comment]
Running with "-e agent.disableupdate=true" doesn't appear to help the situation. Once Azure DevOps asks the agent to update itself, it also no longer schedules any work to that agent, so it is effectively disabled after it has been asked to update.
