### ISSUE TITLE
vsts docker agent fails with exit code 127 while launching task in a docker container

### ISSUE THREAD

**Issue by VarunkumarManohar** [Microsoft/vsts-agent-docker#75]
Visualstudio.com
https://varungb.visualstudio.com

I run a private vsts agent inside a docker container

```
docker run -e VSTS_ACCOUNT=<vstsaccount> -e VSTS_TOKEN=<vstspat> -e 
VSTS_WORK=/var/vsts -v /var/run/docker.sock:/var/run/docker.sock  
-v D:/dockertestmount:/var/vsts 
-d microsoft/vsts-agent:ubuntu-16.04-docker-17.03.0-ce-standard
```
With the invocation of this docker command, I see a successful agent registration inside vsts online agent queue.

I am trying to use this preview feature to start a task inside a docker container from this vsts agent (which itself is a docker container in this case)

[RunTaskInDocker](https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/runtaskindocker.md)
That means the docker vsts agent container will listen for build requests and when there is one, it will start a task in another docker container.

The yaml file I am trying to use in the build definition is:

```
phases:
- phase: consoleappbuild
  variables:
    _PREVIEW_VSTS_DOCKER_IMAGE: "microsoft/dotnet-nightly"
  queue: Default
  steps:
  - bash: |
        cd ConsoleApp1
        dotnet restore
        dotnet build
```
With the usage of this vsts yaml file, I see that a new container gets launched by the vsts docker agent to build.

The sources were downloaded as well in the the new task docker container.

But during build the task container exits abruptly with the error code:

```
2018-02-13T19:10:21.7956034Z bash: line 0: cd: /var/vsts/2/s: No such file or directory
2018-02-13T19:10:21.7981864Z bash: /vsts/agent/externals/node/bin/node: No such file or directory
[error]Exit code 127 returned from process: file name
'/usr/local/bin/docker', arguments 'exec -u 0  -e "INPUT_TARGETTYPE=inline" 
-e "INPUT_FILEPATH=/var/vsts/1/s" -e "INPUT_ARGUMENTS=" -e 
"INPUT_SCRIPT=cd ConsoleApp1 ----
```
What is the cause of error in this control flow ?
Also note that if I queue the same vsts yaml build definition is VS Hosted Linux Preview, the build succeeds. Builds fails only when using a private vsts agent.

**Comment by VarunkumarManohar** [comment]
seems like the issue is with volume mounting. The task container is unable to use the mounted volume.

I have checked the logs and the task container was created with volume mounting on /var/vsts/1/s and
/var/agent/external

**Comment by dakale** [comment]
I was able to reproduce this issue.

I shelled into my private agent container and ran the `docker create` from the build logs:

(`docker create --name ... --rm -v /var/run/docker.sock:/var/run/docker.sock  -v /var/vsts/1:/var/vsts/1 -v "/var/vsts/_temp":"/var/vsts/_temp" -v "/var/vsts/_tool":"/var/vsts/_tool" -v "/vsts/agent/externals":"/vsts/agent/externals":ro -v "/var/vsts/_tasks":"/var/vsts/_tasks":ro -v "/var/vsts/.taskkey":"/var/vsts/.taskkey" microsoft/dotnet-nightly sleep 999d`)

If I start this container and shell into it there is a `/var/vsts` directory but not a `/var/vsts/2/s` as you observed

The empty directory is created by the the bind mount `-v` but because bind mounts bind to a directory in the host machine (https://docs.docker.com/storage/bind-mounts/) the path as given from inside the agent container does not map to a directory on the host machine- the agent may need to switch to using named volume mounts or perhaps DinD instead of bind mounting Docker socket. 

At this time I think this may be a bug with the vsts-agent, not necessarily this repo, because that is what generates the command to create the sibling task container. 

cc @TingluoHuang who I think may have some insight into this area (but is currently on vacation)

**Comment by chrisrpatterson** [comment]
Running the agent in a container and running a task in a container are not really compatible with each other.  DinD might help and that is something you could do by building your own DinD container.

**Comment by stepro** [comment]
Assuming the only bind mounts that the containerized task requires are /var/agent/external and /var/vsts/*/s, you should be able to make this work as follows:
- Run a preliminary agent from the host: `docker run --name vsts-agent -e VSTS_ACCOUNT=... -e VSTS_TOKEN=... -it --rm microsoft/vsts-agent`
- Once this is connected and listening for jobs, execute this on the host: `mkdir /vsts/agent && cd /vsts/agent && docker cp vsts-agent:/vsts/agent/externals .`
- Now remove the preliminary agent: `docker stop vsts-agent`
- Finally, run your actual agent with the following bind mount:
  - -v /var/vsts:/var/vsts

These instructions will ensure that the task running in a container is successfully about to bind mount /vsts/agent/externals and /var/vsts/... Let me know if it doesn't work.

**Comment by chrisrpatterson** [comment]
I am not sure running an agent in a container and then launching another container to bind mount the same paths that are mounted in the agent container is going to work well in the long run.  It seems like a lot of path mapping to keep straight.
